compute_image:
    number_of_frames: all
show_movie:
    image: average_image
    annotate: False
find_coordinates:
    channels:
        - donor
    projection_image_type: average # Choose average or maximum
    method: by_channel # Choose by_channel, average_channels or sum_channels
    window_size: 20
    use_sliding_window: False
    minimal_point_separation: 2
    peak_finding:
        method: local-maximum
        minimum_intensity_difference: 10
        maximum_intensity_difference: 40  # Optional
    coordinate_optimization:
        coordinates_within_margin:
            margin: 20
        coordinates_after_gaussian_fit:
            gaussian_width: 9
        coordinates_without_intensity_at_radius:
            radius: 4
            cutoff: image_median
            fraction_of_peak_max: 0.25
mapping:
    method: icp # Choose icp and nn
    distance_threshold: 3 # Only relevant for nn or icp
    transformation_type: nonlinear # Choose linear, nonlinear or polynomial
    initial_translation: 'width/2' # Or e.g. [1024,0]
    peak_finding:
        donor:
            method: local-maximum
            minimum_intensity_difference: 200
        acceptor:
            method: local-maximum
            minimum_intensity_difference: 50
    coordinate_optimization:
        coordinates_after_gaussian_fit:
            gaussian_width: 9
        coordinates_without_intensity_at_radius:
            radius: 4
            cutoff: image_median
            fraction_of_peak_max: 0.35
        coordinates_within_margin:
            margin: 20
trace_extraction:
    channel: 'all'
    gaussian_width: 11