name: trace_analysis
channels:
- conda-forge
dependencies:
- python=3.7
- pip=19.3.1
- numpy=1.17.*
- matplotlib=3.1.*
- wxpython=4.0.6
- pathlib2=2.3.4
- opencv=4.1.1
- tabulate=0.8.3
- scipy=1.3.*
- scikit-image=0.15.*
- scikit-learn=0.21.*
- pyyaml=5.1.2
- pandas=0.25.1
- seaborn=0.9.0
- openpyxl=3.0.1
- sphinx=2.3.1
- sphinx_rtd_theme=0.4.3
- git=2.23.0
- pip:
    - tifffile==2019.7.26
